# Generated by Django 3.2 on 2021-04-28 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gStock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=gStock.models.get_next_sorties_ref, help_text='Référence', max_length=12, unique=True, verbose_name='Reference')),
                ('data', models.TextField(verbose_name='Articles')),
                ('observation', models.TextField(blank=True, max_length=1000, verbose_name='Observation')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date De Création')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=gStock.models.get_next_entrees_ref, help_text='Référence', max_length=12, unique=True, verbose_name='Reference')),
                ('data', models.TextField(verbose_name='Articles')),
                ('observation', models.TextField(blank=True, max_length=1000, verbose_name='Observation')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date De Création')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorize_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Catégorie : Employee/Prestataire/Client/etc', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Article Unit', max_length=50, verbose_name='Unit')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom complet de l'article", max_length=200, verbose_name='Name')),
                ('articleModel', models.CharField(help_text="Modèle de l'article", max_length=200, verbose_name='Model')),
                ('reference', models.CharField(blank=True, help_text="La référence de l'article ou le numéro de série.", max_length=50)),
                ('ean', models.CharField(default=gStock.models.get_next_ean, help_text='The EAN13 code for the product, i.e. 12 digits. Proposed automatically. Should start with ART for internal codes.', max_length=12, unique=True, validators=[gStock.models.validate_ean])),
                ('stock', models.IntegerField(help_text="La quantité d'articles en stock")),
                ('position', models.TextField(blank=True, help_text="La position de l'article informe sur l'endroit où se trouve ce dernier.", max_length=1000)),
                ('description', models.TextField(blank=True, help_text="Description de l'article. Mentionner l'état defectueux ou non de l'article.", max_length=1000)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gStock.articleunit')),
            ],
            options={
                'ordering': ['name', 'reference'],
                'unique_together': {('name', 'articleModel', 'unit')},
            },
        ),
    ]
