# Generated by Django 3.2 on 2021-04-28 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gStock', '0002_auto_20210428_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date De Création'),
            preserve_default=False,
        ),
    ]
