# Generated by Django 3.2 on 2021-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gStock', '0004_rename_categorize_user_categorizeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='motif',
            field=models.TextField(default=' ', verbose_name='Motif'),
            preserve_default=False,
        ),
    ]
