# Generated by Django 3.2 on 2021-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gStock', '0006_auto_20210429_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='threshold',
            field=models.IntegerField(default=5, help_text='Threshold from which to automatically replenish the product'),
        ),
    ]
