# Generated by Django 3.2 on 2021-05-03 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gStock', '0007_article_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleunit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date De Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorizeuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date De Création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='proprietaire',
            field=models.CharField(help_text="Propriétaire de l'article.", max_length=100),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of supplier', max_length=200)),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, help_text='E-mail', max_length=254, verbose_name='E-Mail')),
                ('site_web', models.CharField(blank=True, help_text='Le site web du fournisseur', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Mention the products that the supplier sells, its area of intervention, etc.', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date De Création')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Produit', help_text='Produit', max_length=100)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Buying price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Sell price')),
                ('tva', models.DecimalField(decimal_places=2, default=0.18, max_digits=3, verbose_name='Taux de TVA')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date De Création')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gStock.article')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gStock.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Materiel', help_text='Produit', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date De Création')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gStock.article')),
            ],
        ),
    ]
